# Generated by Django 5.1.2 on 2024-12-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
