# Generated by Django 5.1.2 on 2024-12-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_station_registration',
            name='usertype',
            field=models.CharField(default='station', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_type',
            field=models.CharField(default='staff', max_length=50),
        ),
    ]
