# Generated by Django 5.1.2 on 2024-12-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0004_police_station_registration_usertype_staff_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police_station_registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='police_station_registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='police_station_registration',
            name='usertype',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_type',
        ),
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(default='station', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='police_station_registration',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mini.login'),
        ),
        migrations.AddField(
            model_name='staff',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mini.login'),
        ),
    ]
