# Generated by Django 5.1.2 on 2025-03-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0005_remove_police_station_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
