# Generated by Django 5.1.2 on 2025-03-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0006_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('login_if', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mini.login')),
            ],
        ),
    ]
