# Generated by Django 5.1.2 on 2025-03-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0007_user_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='login_if',
            new_name='login_id',
        ),
    ]
