# Generated by Django 5.1.2 on 2025-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0008_rename_login_if_user_registration_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20),
        ),
    ]
