# Generated by Django 5.1.2 on 2025-03-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0009_alter_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
