# Generated by Django 5.2 on 2025-04-12 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0010_alter_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='varification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_data', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('reply', models.TextField(null=True)),
                ('station_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.police_station_registration')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.user_registration')),
            ],
        ),
    ]
