# Generated by Django 5.2 on 2025-04-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0011_login_varification_status_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.police_station_registration'),
        ),
    ]
