# Generated by Django 5.2 on 2025-04-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0012_staff_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition_text', models.TextField()),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.police_station_registration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.user_registration')),
            ],
        ),
    ]
