# Generated by Django 5.2 on 2025-04-13 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0013_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
