# Generated by Django 5.2 on 2025-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0014_petition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
