# Generated by Django 5.2 on 2025-04-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0015_petition_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('case', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('photo', models.ImageField(null=True, upload_to='criminal_photo/')),
            ],
        ),
    ]
