# Generated by Django 5.2 on 2025-04-15 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0016_criminalregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalregistration',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminalregistration',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='criminalregistration',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.police_station_registration'),
        ),
        migrations.AddField(
            model_name='criminalregistration',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
