# Generated by Django 5.2 on 2025-04-16 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0017_criminalregistration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('complainant_name', models.CharField(max_length=100)),
                ('complainant_address', models.TextField()),
                ('complainant_contact', models.CharField(max_length=15)),
                ('accused_name', models.CharField(blank=True, max_length=100, null=True)),
                ('accused_address', models.TextField(blank=True, null=True)),
                ('incident_date', models.DateTimeField()),
                ('incident_location', models.TextField()),
                ('description_of_incident', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='fir_evidence/')),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('investigating', 'Investigating'), ('charge_sheeted', 'Charge Sheeted'), ('closed', 'Closed')], default='filed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.police_station_registration')),
            ],
        ),
    ]
