# Generated by Django 5.2 on 2025-04-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0018_fir'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='petitionIinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.petition'),
        ),
    ]
