# Generated by Django 5.2 on 2025-04-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0019_fir_petitioniinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='petitionIinfo',
            new_name='petitionInfo',
        ),
    ]
