# Generated by Django 5.2 on 2025-04-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0020_rename_petitioniinfo_fir_petitioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='fir_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
