# Generated by Django 5.2 on 2025-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0021_alter_fir_fir_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='fir_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
