# Generated by Django 5.2 on 2025-04-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0022_petition_fir_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheduleDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('staff_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.staff')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.police_station_registration')),
            ],
        ),
    ]
