# Generated by Django 5.2 on 2025-04-21 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0023_sheduleduty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.staff')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mini.police_station_registration')),
            ],
        ),
    ]
