# Generated by Django 5.2 on 2025-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0024_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att',
            field=models.CharField(max_length=6),
        ),
    ]
