# Generated by Django 5.2 on 2025-04-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0025_alter_attendance_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att',
            field=models.CharField(max_length=10),
        ),
    ]
