# Generated by Django 5.2 on 2025-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0026_alter_attendance_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('DGP', 'Director General of Police'), ('IGP', 'Inspector General of Police'), ('SP', 'Superintendent of Police'), ('DSP', 'Deputy Superintendent of Police'), ('CI', 'Circle Inspector'), ('SI', 'Sub Inspector'), ('ASI', 'Assistant Sub Inspector'), ('HC', 'Head Constable'), ('PC', 'Police Constable')], max_length=50),
        ),
    ]
