# Generated by Django 5.2 on 2025-04-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0030_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
