# Generated by Django 5.2 on 2025-04-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0032_alter_salary_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='salary',
            new_name='bs',
        ),
        migrations.AddField(
            model_name='salary',
            name='da',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='hr',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='pf',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='total_salaty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
