# Generated by Django 5.2 on 2025-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0034_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='msg',
            field=models.TextField(),
        ),
    ]
