# Generated by Django 5.2 on 2025-05-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0035_alter_complaint_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
