# Generated by Django 5.2 on 2025-05-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0036_user_registration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='pro_pic',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
