# Generated by Django 5.2 on 2025-05-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0037_user_registration_pro_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='pro_pic',
            new_name='profile_picture',
        ),
    ]
