# Generated by Django 5.2 on 2025-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0038_rename_pro_pic_user_registration_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_staff/'),
        ),
    ]
