# Generated by Django 5.2 on 2025-06-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0039_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='adhar',
            field=models.IntegerField(default=567876543456),
            preserve_default=False,
        ),
    ]
