# Generated by Django 5.2 on 2025-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0040_user_registration_adhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='bs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='da',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
