# Generated by Django 5.2 on 2025-07-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0041_alter_salary_bs_alter_salary_da_alter_salary_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='complainant_contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='police_station_registration',
            name='contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='contact',
            field=models.CharField(max_length=13),
        ),
    ]
