# Generated by Django 5.2 on 2025-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0042_alter_fir_complainant_contact_alter_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
