# Generated by Django 5.2 on 2025-08-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini', '0043_alter_staff_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6),
        ),
    ]
